version: "3.9"

services:
  nodejs-app:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/app
      - /app/node_modules
