version: "3.9"

services:
  go-app:
    build:
      context: .
      dockerfile: docker/Dockerfile-dev
    ports:
      - "2345:2345"
      - "8080:8080"
    volumes:
      - .:/app
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
